feat: allow mine nft creation transaction
HathorNetwork/tx-mining-service pull request #32
Opened 2021-09-16 14:50 UTC by pedroferreira1

2021-09-21 07:46 UTC, msbrogli requested changes

2021-09-21 07:46 UTC, msbrogli commented on txstratum/api.py
> +            if self.only_standard_script and not is_nft_creation:
This code is outdated, isn't it?

2021-09-22 20:52 UTC, pedroferreira1 commented on txstratum/api.py
> +            if self.only_standard_script and not is_nft_creation:
Yes, can you see again please?

2021-09-22 21:24 UTC, msbrogli approved these changes

2021-09-22 21:24 UTC, msbrogli commented on tests/test_api.py
> +        self.assertEqual({'error': 'tx-non-standard'}, data)
I'd call it `non-standard-tx`.

2021-09-22 21:24 UTC, msbrogli commented on tests/test_api.py
> +        self.assertEqual({'error': 'tx-non-standard'}, data)
I'd call it `non-standard-tx`.

2021-09-22 21:24 UTC, msbrogli commented on txstratum/api.py
> +            return web.json_response({'error': 'tx-non-standard'}, status=400)
I'd call it `non-standard-tx`.

2021-09-23 01:06 UTC, jansegre approved these changes

2021-09-23 19:24 UTC, pedroferreira1 commented on tests/test_api.py
> +        self.assertEqual({'error': 'tx-non-standard'}, data)
Done

2021-09-23 19:24 UTC, pedroferreira1 commented on tests/test_api.py
> +        self.assertEqual({'error': 'tx-non-standard'}, data)
Done

2021-09-23 19:24 UTC, pedroferreira1 commented on txstratum/api.py
> +            return web.json_response({'error': 'tx-non-standard'}, status=400)
Done

2021-09-23 19:25 UTC, merged